# Generated by Django 2.1 on 2018-08-23 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('image_thumbnail', models.ImageField(null=True, upload_to='category/thumbnail')),
                ('image_background', models.ImageField(null=True, upload_to='category/background')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('image_thumbnail', models.ImageField(null=True, upload_to='service/thumbnail')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('approx_time', models.CharField(default='test', max_length=100)),
                ('difficulty', models.CharField(choices=[('Normal', 'Normal'), ('Prestige', 'Prestige')], default='Normal', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', related_query_name='services', to='services.Category')),
            ],
        ),
    ]
