# Generated by Django 2.1 on 2018-08-31 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('Normal', 'Normal'), ('Prestige', 'Prestige')], default='Normal', max_length=10)),
                ('approx_time', models.DurationField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('level_requirement', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='approx_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
        ),
    ]
