# Generated by Django 2.1 on 2018-08-31 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180831_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconfig',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config', related_query_name='config', to='services.Service'),
        ),
    ]
