# Generated by Django 2.1 on 2018-08-31 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20180831_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceconfig',
            options={'ordering': ('difficulty',)},
        ),
        migrations.AlterField(
            model_name='serviceconfig',
            name='difficulty',
            field=models.CharField(choices=[('Normal', 'normal'), ('Prestige', 'prestige')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='serviceconfig',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', related_query_name='configs', to='services.Service'),
        ),
    ]
