# Generated by Django 2.1 on 2018-09-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20180831_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfig',
            name='additional_info',
            field=models.CharField(blank=True, max_length=500, verbose_name='Additional info'),
        ),
    ]
