# Generated by Django 2.1 on 2018-09-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceconfig_additional_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceconfig',
            options={'ordering': ('mode_name',)},
        ),
        migrations.RemoveField(
            model_name='serviceconfig',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='mode_name',
            field=models.CharField(default='Normal', max_length=200),
            preserve_default=False,
        ),
    ]
