# Generated by Django 2.1 on 2018-09-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20180906_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='service',
            name='select_many_modes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviceconfig',
            name='mode_name',
            field=models.CharField(max_length=200, verbose_name='Service mode name'),
        ),
    ]
