# Generated by Django 2.1 on 2018-09-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20180906_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfig',
            name='is_inner_only',
            field=models.BooleanField(default=False),
        ),
    ]
