# Generated by Django 2.1 on 2018-09-07 11:44

import django.core.validators
import rest_framework.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_serviceconfig_is_inner_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('discount', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('service', models.ManyToManyField(related_name='promo_codes', related_query_name='promo_codes', to='services.Service')),
            ],
            options={
                'verbose_name': 'Promo code',
                'verbose_name_plural': 'Promo codes',
            },
        ),
        migrations.AlterModelOptions(
            name='serviceconfig',
            options={'ordering': ('ordering',)},
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
