# Generated by Django 2.1 on 2018-09-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20180907_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
