# Generated by Django 2.1 on 2018-12-05 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20180909_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLayout',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Promo code',
                'verbose_name_plural': 'Promo codes',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='layout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.CategoryLayout'),
        ),
    ]
