# Generated by Django 2.1 on 2018-12-08 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20181205_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='PvpThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_price', models.DecimalField(decimal_places=0, help_text='Price', max_digits=5)),
                ('step_value', models.PositiveSmallIntegerField(help_text='Value for step of range slider')),
                ('threshold_points', models.PositiveIntegerField(help_text='Points threshold')),
                ('threshold_label', models.CharField(help_text='Value on range corresponding rank', max_length=64)),
            ],
            options={
                'verbose_name': 'Pvp threshold config',
                'verbose_name_plural': 'Pvp thresholds config',
            },
        ),
        migrations.CreateModel(
            name='ServiceConfigPvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.CharField(blank=True, max_length=500, verbose_name='Additional info')),
                ('max_points', models.PositiveIntegerField(help_text='Max amount of points')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
            options={
                'verbose_name': 'Pvp threshold config',
                'verbose_name_plural': 'Pvp thresholds config',
            },
        ),
        migrations.AlterModelOptions(
            name='categorylayout',
            options={'verbose_name': 'Category layout', 'verbose_name_plural': 'Category layout'},
        ),
        migrations.AddField(
            model_name='pvpthreshold',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceConfigPvp'),
        ),
    ]
