# Generated by Django 2.1 on 2019-02-09 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20190202_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_background',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_thumbnail',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, help_text='Displayed in a modal winodw', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, help_text='Displayed on card', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.CategoryLayout'),
        ),
    ]
