# Generated by Django 2.1 on 2019-02-20 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20190209_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='approx_time',
            field=models.DurationField(blank=True, help_text='Service config settings will be overwritten', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='layout',
            field=models.ForeignKey(blank=True, help_text='You can overwrite category layout in service. Category layout will be ignored', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.CategoryLayout'),
        ),
        migrations.AddField(
            model_name='service',
            name='level_requirement',
            field=models.IntegerField(blank=True, help_text='Service config settings will be overwritten', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, help_text='Displayed in a modal window', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='serviceconfig',
            name='approx_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceconfig',
            name='level_requirement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
