# Generated by Django 2.1 on 2019-02-24 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('services', '0017_auto_20190220_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site'),
        ),
    ]
