# Generated by Django 2.1 on 2019-02-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20190224_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvpthreshold',
            name='step_price',
            field=models.DecimalField(decimal_places=2, help_text='Price', max_digits=5),
        ),
    ]
