# Generated by Django 2.1 on 2019-03-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20190225_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
