# Generated by Django 2.1 on 2019-03-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_service_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfig',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Optional discount', max_digits=5, null=True),
        ),
    ]
