# Generated by Django 2.1 on 2019-03-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_serviceconfig_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='show_discount',
            field=models.BooleanField(default=False),
        ),
    ]
