# Generated by Django 2.1 on 2019-03-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_auto_20190318_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfigpvp',
            name='first_mark_text',
            field=models.CharField(default='Guardian', help_text='Text for first point', max_length=128),
        ),
        migrations.AddField(
            model_name='serviceconfigpvp',
            name='initial_pints',
            field=models.IntegerField(default=0, help_text='Points of user to start'),
        ),
        migrations.AddField(
            model_name='serviceconfigpvp',
            name='initial_points_selected',
            field=models.PositiveIntegerField(default=10, help_text='Initial amount of points'),
        ),
        migrations.AddField(
            model_name='serviceconfigpvp',
            name='min_points',
            field=models.PositiveIntegerField(default=0, help_text='Min amount of points'),
        ),
    ]
