# Generated by Django 2.1 on 2019-03-18 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_auto_20190318_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceconfigpvp',
            old_name='initial_pints',
            new_name='initial_points',
        ),
    ]
