# Generated by Django 2.1 on 2019-06-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_auto_20190616_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image_thumbnail',
        ),
        migrations.RemoveField(
            model_name='serviceconfig',
            name='approx_time',
        ),
        migrations.RemoveField(
            model_name='serviceconfig',
            name='level_requirement',
        ),
    ]
