# Generated by Django 2.1 on 2019-06-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_service_option_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_square',
            field=models.ImageField(blank=True, upload_to='uploaded_images'),
        ),
    ]
