# Generated by Django 2.1 on 2019-06-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_auto_20190630_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='card_image',
            field=models.ImageField(blank=True, upload_to='uploaded_images_bg'),
        ),
    ]
