# Generated by Django 2.1 on 2019-07-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_service_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='item_image',
            field=models.ImageField(blank=True, upload_to='uploaded_item_images'),
        ),
    ]
