# Generated by Django 2.1 on 2019-07-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_auto_20190720_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
