# Generated by Django 2.1 on 2019-07-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0040_auto_20190720_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название сезона', max_length=64)),
                ('slug', models.CharField(help_text='Slug сезона', max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='seasons',
            field=models.ManyToManyField(related_name='seasons', related_query_name='seasons', to='services.Season'),
        ),
    ]
