# Generated by Django 2.1 on 2019-07-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0042_auto_20190721_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='seasons',
            field=models.ManyToManyField(blank=True, related_name='seasons', related_query_name='seasons', to='services.Season'),
        ),
    ]
