# Generated by Django 2.1 on 2019-10-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0045_service_extra_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfig',
            name='booster_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
