# Generated by Django 2.1 on 2019-11-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0047_auto_20191031_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='usage_limit',
            field=models.IntegerField(default=10),
        ),
    ]
