# Generated by Django 2.1 on 2020-03-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0048_promocode_usage_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="first_buy_only",
            field=models.BooleanField(default=False),
        ),
    ]
