# Generated by Django 2.1 on 2020-05-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0049_promocode_first_buy_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='booster_price',
        ),
    ]
