# Generated by Django 2.1 on 2020-05-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0050_remove_service_booster_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='booster_price',
            field=models.IntegerField(default=50),
        ),
    ]
