# Generated by Django 3.0.8 on 2020-10-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0051_service_booster_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroupTagORM',
            fields=[
                ('value', models.CharField(max_length=58, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=58)),
            ],
            options={
                'verbose_name': 'Main Page Group Tag',
                'verbose_name_plural': 'Main Page Group tags',
                'db_table': 'service_group_tag',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='group_tags',
            field=models.ManyToManyField(blank=True, related_name='group_tags', related_query_name='group_tags', to='services.ServiceGroupTagORM'),
        ),
    ]
