# Generated by Django 3.0.8 on 2020-11-08 08:30
import core.domain.entities.constants
import core.domain.entities.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0052_auto_20201010_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='configuration_options',
            field=models.CharField(null=True, blank=True, choices=[(core.domain.entities.constants.ConfigurationType['base_price'], 'Base price'), (
            core.domain.entities.constants.ConfigurationType['options_select'], 'Options select'), (
                                                                   core.domain.entities.constants.ConfigurationType['range_select'], 'Range select'), (
                                                                   core.domain.entities.constants.ConfigurationType['options_steps'], 'Options steps')], default=None, max_length=20),
        ),
    ]
