# Generated by Django 3.0.8 on 2020-11-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0055_auto_20201113_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='at_least_one_option_required',
            field=models.BooleanField(default=False),
        ),
    ]
