# Generated by Django 3.0.8 on 2020-11-29 11:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0056_service_at_least_one_option_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='you_will_get_content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
