# Generated by Django 3.0.8 on 2020-11-29 12:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0057_service_you_will_get_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='static_description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='static_requirements',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='you_will_get_content',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
