# Generated by Django 3.0.8 on 2021-01-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0058_auto_20201129_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegrouptagorm',
            name='services',
            field=models.ManyToManyField(blank=True, to='services.Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='group_tags',
            field=models.ManyToManyField(blank=True, to='services.ServiceGroupTagORM'),
        ),
    ]
