# Generated by Django 3.0.8 on 2021-01-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0060_auto_20210107_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicegrouptagorm',
            options={'verbose_name': 'Main Page Group Tag', 'verbose_name_plural': 'Main Page Group tags'},
        ),
        migrations.RemoveField(
            model_name='servicegrouptagorm',
            name='ordering',
        ),
    ]
