version: '3.7'

x-postgres-enviroments: &postgres-enviroments
  POSTGRES_USER: 'boosting'
  POSTGRES_PASSWORD: 'sumes241oefsarasdea342'
  POSTGRES_HOST: 'database'

services:
  backend:
    build:
      .
    entrypoint: ./scripts/backend-start.sh
    volumes:
      - ./src:/opt/app/src:delegated
      - ./static_in_env:/opt/app/static_in_env:delegated
    environment:
      <<: *postgres-enviroments
      DEBUG: 'True'
      config__ENVIRONMENT: 'development'
      EMAIL_HOST: 'smtp.yandex.ru'
      EMAIL_PORT: '587'
      EMAIL_HOST_USER: 'no-reply@littlelight.store'
      EMAIL_HOST_PASSWORD: 'cyczyT-teqfu0-dadxuf'
      BASE_AUTH_URL: 'http://localhost:3000'
      REDIS_HOST: 'redis'
      PUSH_GOOGLE_TOKEN: 'AAAAGHA_gfA:APA91bGOY0SMJmcaxga0jWS_-5iFwkBr3aIJ1nteF1HGcLocX_47h9LahZsTKbTAUGEBnJaFyt-_bcCG6vb3sPu71x0AN_yWyUejG0rUgIcLOPHneKx23AzIWWY0DzA34osjfw_F75kV'
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres:10
    hostname: database
    environment:
      <<: *postgres-enviroments
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:delegated

