# Generated by Django 2.1 on 2019-09-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0045_service_extra_categories'),
        ('reviews', '0010_auto_20190908_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='services',
            field=models.ManyToManyField(to='services.Service'),
        ),
    ]
