# Generated by Django 2.1 on 2019-09-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20190908_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_sent_to_user',
            field=models.BooleanField(default=False),
        ),
    ]
