# Generated by Django 2.1 on 2019-09-08 14:40

from django.db import migrations, models

import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_review_is_sent_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='edit_token',
            field=models.CharField(default=reviews.models.create_edit_token, max_length=128),
        ),
    ]
