# Generated by Django 3.0.8 on 2021-01-11 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0075_auto_20210111_1838'),
        ('reviews', '0017_auto_20190909_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='client_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.ORMClientOrder'),
        ),
    ]
