# Generated by Django 2.1 on 2019-11-23 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0048_promocode_usage_limit"),
    ]

    operations = [
        migrations.CreateModel(
            name="GamePage",
            fields=[
                (
                    "game",
                    models.CharField(
                        db_index=True, max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("total_boosters", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="LimitedOffer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=100)),
                ("promo", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="PromotedBlock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("image", models.ImageField(upload_to="pages/game-page/")),
                (
                    "link_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.Service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceOfTheWeek",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=100)),
                (
                    "background_image",
                    models.ImageField(upload_to="pages/game-page/of-the-week/"),
                ),
                (
                    "link_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.Service",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gamepage",
            name="block_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="block_1",
                to="pages.PromotedBlock",
            ),
        ),
        migrations.AddField(
            model_name="gamepage",
            name="block_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="block_2",
                to="pages.PromotedBlock",
            ),
        ),
        migrations.AddField(
            model_name="gamepage",
            name="offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="pages.LimitedOffer",
            ),
        ),
        migrations.AddField(
            model_name="gamepage",
            name="service_of_the_week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_of_the_week",
                to="pages.ServiceOfTheWeek",
            ),
        ),
    ]
