# Generated by Django 2.1 on 2019-11-23 12:55

from django.db import migrations


def combine_names(apps, schema_editor):
    apps.get_model("pages", "GamePage").objects.get_or_create(
        game="destiny2", defaults={"total_boosters": 37}
    )


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_auto_20191123_1242"),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
