# Generated by Django 2.1 on 2019-11-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_auto_20191123_1255"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotedblock",
            name="description",
            field=models.CharField(default="", max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="promotedblock",
            name="title",
            field=models.CharField(max_length=40),
        ),
    ]
