# Generated by Django 2.1 on 2019-11-24 11:05

from django.db import migrations

from profiles.orm_models import ORMDestinyBungieProfile


def combine_names(apps, schema_editor):
    destiny2_page = apps.get_model("pages", "GamePage").objects.get(game="destiny2")


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_auto_20191123_1348"),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
