# Generated by Django 2.1 on 2019-02-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_order_bungie_profile'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bungieid',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='profilecredentials',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='usercharacter',
            name='bungie_profile',
        ),
        migrations.DeleteModel(
            name='BungieID',
        ),
    ]
