# Generated by Django 2.1 on 2019-02-17 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190217_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='BungieID',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('membership_id', models.CharField(max_length=500)),
                ('membership_type', models.CharField(choices=[('Xbox', 1), ('Playstaion', 2), ('Battlenet', 4)], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bungie_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profilecredentials',
            name='membership',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='credentails', to='profiles.BungieID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercharacter',
            name='bungie_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='profiles.BungieID'),
        ),
    ]
