# Generated by Django 2.1 on 2019-02-25 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190217_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoosterConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(help_text='Booster telegram', max_length=100)),
                ('rating', models.IntegerField(default=0, help_text='User rating', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_booster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boosterconfig',
            name='platforms',
            field=models.ManyToManyField(help_text='Booster platforms', related_name='boosters', to='profiles.Platforms'),
        ),
        migrations.AddField(
            model_name='user',
            name='booster_config',
            field=models.OneToOneField(blank=True, help_text='Booster config', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='profiles.BoosterConfig'),
        ),
    ]
