# Generated by Django 2.1 on 2019-02-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190225_1702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Platforms',
            new_name='Platform',
        ),
        migrations.AlterField(
            model_name='boosterconfig',
            name='rating',
            field=models.IntegerField(default=0, help_text='User rating'),
        ),
    ]
