# Generated by Django 2.1 on 2019-02-25 17:03

from django.db import migrations


def combine_names(apps, schema_editor):
    for platform in ['xbox', 'ps4', 'desktop']:
        apps.get_model("profiles", "Platform").objects.create(name=platform)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190225_1706'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
