# Generated by Django 2.1 on 2019-02-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20190225_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boosteruser',
            options={'verbose_name': 'Booster user', 'verbose_name_plural': 'Boosters'},
        ),
    ]
