# Generated by Django 2.1 on 2019-03-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20190225_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bungieid',
            name='membership_type',
            field=models.CharField(choices=[('Xbox', 1), ('PS4', 2), ('BattleNET', 4)], max_length=20),
        ),
    ]
