# Generated by Django 2.1 on 2019-04-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20190316_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bungieid',
            name='membership_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usercharacter',
            name='character_class',
            field=models.CharField(max_length=10),
        ),
    ]
