# Generated by Django 2.1 on 2019-09-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_emailsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='bungieid',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
