# Generated by Django 2.1 on 2019-09-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_contactinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinformation',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='discord',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ContactInformation',
        ),
    ]
