# Generated by Django 2.1 on 2019-09-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20190922_1646'),
    ]

    operations = [
    ]
