# Generated by Django 2.1 on 2019-10-02 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20190926_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booster_profile',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='profiles.BoosterUser'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_booster',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
