# Generated by Django 2.1 on 2019-10-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20191002_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boosteruser',
            name='platforms',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
