# Generated by Django 2.1 on 2019-10-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20191012_1856'),
    ]

    operations = [
    ]
