# Generated by Django 2.1 on 2019-10-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_auto_20191012_1858'),
    ]

    operations = [
    ]
