# Generated by Django 2.1 on 2019-10-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_auto_20191012_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bungieplatform',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
