# Generated by Django 2.1 on 2019-10-12 19:02

from django.db import migrations


def combine_names(apps, schema_editor):
    for platform in ([1, 'XBOX'], [2, 'PlayStation'], [3, 'Steam'], [4, 'Battle.NET']):
        value, name = platform
        apps.get_model("profiles", "BungiePlatform").objects.create(value=value, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_auto_20191012_1901'),
    ]

    operations = [
        migrations.RunPython(combine_names)
    ]
