# Generated by Django 2.1 on 2019-10-13 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authtoken', '0002_auto_20160226_1747'),
        ('orders', '0042_remove_order_booster_user'),
        ('drfpasswordless', '0001_initial'),
        ('reviews', '0017_auto_20190909_0400'),
        ('profiles', '0027_auto_20191012_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boosteruser',
            name='platforms',
        ),
        migrations.RemoveField(
            model_name='boosteruser',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='booster_profile',
        ),
        migrations.DeleteModel(
            name='BoosterUser',
        ),
    ]
