# Generated by Django 2.1 on 2019-10-13 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_auto_20191013_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoosterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(help_text='Booster telegram', max_length=100)),
                ('rating', models.IntegerField(default=0, help_text='User rating')),
                ('platforms', models.ManyToManyField(help_text='Booster platforms', related_name='boosters', to='profiles.BungiePlatform')),
            ],
            options={
                'verbose_name': 'Booster user',
                'verbose_name_plural': 'Boosters',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='booster_profile',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='profiles.BoosterUser'),
        ),
    ]
