# Generated by Django 2.1 on 2019-10-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_auto_20191013_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boosteruser',
            name='telegram',
        ),
    ]
