# Generated by Django 2.1 on 2019-10-13 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_remove_boosteruser_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='booster_profile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='profiles.BoosterUser'),
        ),
    ]
