# Generated by Django 2.1 on 2019-10-13 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_auto_20191013_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='boosteruser',
            name='in_game_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.BungieID'),
        ),
    ]
