# Generated by Django 2.1 on 2019-10-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_boosteruser_in_game_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='boosteruser',
            name='avatar',
            field=models.ImageField(default='', help_text='User avatar', upload_to='boosters'),
        ),
        migrations.AddField(
            model_name='boosteruser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Balance', max_digits=10),
        ),
    ]
