# Generated by Django 2.1 on 2019-10-22 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_boosteruser_total_orders_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecredentials',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.BungiePlatform'),
        ),
        migrations.AlterField(
            model_name='profilecredentials',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='profilecredentials',
            name='extra_contacts',
        ),
        migrations.RemoveField(
            model_name='profilecredentials',
            name='parent_order',
        ),
        migrations.AlterUniqueTogether(
            name='profilecredentials',
            unique_together={('platform', 'owner')},
        ),
    ]
