# Generated by Django 3.0.8 on 2020-07-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0037_auto_20200512_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='boosteruser',
            name='discord_id',
            field=models.CharField(blank=True, default=None, help_text='Discord id. Ex: test#1234', max_length=50, null=True),
        ),
    ]
