# Generated by Django 3.0.8 on 2020-11-16 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_ormdestinybungiecharacter_ormdestinybungieprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormdestinybungiecharacter',
            name='bungie_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destiny_character', to='profiles.ORMDestinyBungieProfile'),
        ),
    ]
