# Generated by Django 3.0.8 on 2021-01-01 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0040_auto_20201116_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormdestinybungieprofile',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
