# Generated by Django 3.0.8 on 2021-01-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0041_ormdestinybungieprofile_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boosteruser',
            name='rating',
            field=models.FloatField(default=0, help_text='User rating'),
        ),
    ]
