# Generated by Django 3.0.8 on 2021-02-21 09:19

from django.db import migrations


def remove_app_duplicates(apps, schema_editor):
    profiles = apps.get_model("profiles", "ORMDestinyBungieProfile").objects.all()

    unique_ids = set()
    for profile in profiles:  # type: "ORMDestinyBungieProfile"
        if profile.client_id in unique_ids:
            profile.client_id = None
            profile.save()
        else:
            unique_ids.add(profile.client_id)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0044_auto_20210221_0917'),
    ]

    operations = [
        migrations.RunPython(remove_app_duplicates)
    ]
