# Generated by Django 3.0.8 on 2021-02-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0047_auto_20210221_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_chat_message_send_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
