# Generated by Django 3.0.8 on 2021-02-22 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0048_user_last_chat_message_send_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='booster_profile',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='profiles.BoosterUser'),
        ),
    ]
