# Generated by Django 3.0.8 on 2021-02-22 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0050_auto_20210222_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormdestinybungieprofile',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destiny_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
