# Generated by Django 3.0.8 on 2021-03-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0052_profilecredentials_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecredentials',
            name='has_second_factor',
            field=models.BooleanField(default=False),
        ),
    ]
