# Generated by Django 3.0.8 on 2021-03-20 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0053_profilecredentials_has_second_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORMNotificationsPurposes',
            fields=[
                ('value', models.CharField(max_length=52, primary_key=True, serialize=False)),
                ('repr', models.CharField(max_length=52)),
            ],
        ),
        migrations.CreateModel(
            name='ORMNotificationsToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
                ('source', models.CharField(choices=[('NotificationTokenType.firebase', 'Source')], max_length=32)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
                ('purposes', models.ManyToManyField(to='profiles.ORMNotificationsPurposes')),
            ],
        ),
    ]
