# Generated by Django 3.0.8 on 2021-03-20 11:46

from django.db import migrations


def generate_notification_purposes(apps, schema_editor):
    for v in [('chat_messages', 'Chat messages'), ('order_status', 'Order statuses')]:
        value, _repr = v
        apps.get_model("profiles", "ORMNotificationsPurposes").objects.create(
            value=value, repr=_repr
        )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0054_ormnotificationspurposes_ormnotificationstoken'),
    ]

    operations = [
        migrations.RunPython(generate_notification_purposes)
    ]
