# Generated by Django 3.0.8 on 2021-03-20 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0055_auto_20210320_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormnotificationstoken',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ormnotificationstoken',
            name='touched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
