# Generated by Django 3.0.8 on 2021-03-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0056_auto_20210320_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormnotificationstoken',
            name='source',
            field=models.CharField(choices=[('firebase', 'Firebase')], max_length=32),
        ),
    ]
