# Generated by Django 2.1 on 2019-02-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.TextField(default='')),
                ('is_order_complete', models.BooleanField(default=False)),
                ('is_payed', models.BooleanField(default=False)),
                ('is_posted', models.BooleanField(default=False)),
                ('data_completed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('taken_at', models.DateTimeField(null=True)),
                ('posted_at', models.DateTimeField(null=True)),
                ('booster_telegram_id', models.CharField(blank=True, max_length=12, null=True)),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PvpConfigOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_points', models.IntegerField()),
                ('to_points', models.IntegerField()),
                ('from_label', models.CharField(max_length=64)),
                ('to_label', models.CharField(max_length=64)),
            ],
        ),
    ]
