# Generated by Django 2.1 on 2019-02-02 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('orders', '0001_initial'),
        ('services', '0015_auto_20190202_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bungie_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.BungieID'),
        ),
        migrations.AddField(
            model_name='order',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.UserCharacter'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', related_query_name='orders', to='services.PromoCode'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ManyToManyField(to='services.ServiceConfig'),
        ),
    ]
