# Generated by Django 2.1 on 2019-02-12 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190202_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pvp_config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.PvpConfigOrder'),
        ),
    ]
