# Generated by Django 2.1 on 2019-02-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190216_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bungie_profile',
        ),
    ]
