# Generated by Django 2.1 on 2019-02-17 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190217_0841'),
        ('orders', '0011_remove_order_bungie_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bungie_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.BungieID'),
        ),
    ]
