# Generated by Django 2.1 on 2019-02-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_booster_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='booster_telegram_id',
        ),
    ]
