# Generated by Django 2.1 on 2019-02-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_order_booster_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='booster_user',
        ),
    ]
