# Generated by Django 2.1 on 2019-03-16 19:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_booster_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='raw_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
