# Generated by Django 2.1 on 2019-04-04 16:17

import django.contrib.postgres.fields.jsonb
import django.contrib.sites.managers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20190404_1617'),
        ('sites', '0002_alter_domain_unique'),
        ('orders', '0018_order_raw_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, default='', max_length=1024)),
                ('payment_status', models.CharField(blank=True, max_length=128, null=True)),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('total_price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('is_payed', models.BooleanField(default=False)),
                ('profile_credentials', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_order', to='profiles.ProfileCredentials')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_orders', to='sites.Site')),
            ],
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='parent_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.ParentOrder'),
        ),
    ]
