# Generated by Django 2.1 on 2019-04-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20190404_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentorder',
            name='profile_credentials',
        ),
    ]
