# Generated by Django 2.1 on 2019-04-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_remove_parentorder_profile_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentorder',
            name='is_seen',
            field=models.BooleanField(default=False, help_text='Set to False to receive tg notification'),
        ),
    ]
