# Generated by Django 2.1 on 2019-08-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_parentorder_is_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data_completed',
            new_name='date_completed',
        ),
        migrations.AlterField(
            model_name='order',
            name='service_config',
            field=models.ManyToManyField(blank=True, null=True, to='services.ServiceConfig'),
        ),
    ]
