# Generated by Django 2.1 on 2019-08-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20190804_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_config',
            field=models.ManyToManyField(blank=True, to='services.ServiceConfig'),
        ),
    ]
