# Generated by Django 2.1 on 2019-08-04 21:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20190804_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='layout_options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
