# Generated by Django 2.1 on 2019-09-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_order_layout_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
