# Generated by Django 2.1 on 2019-09-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('is_checking', 'is_checking'), ('is_payed', 'is_payed'), ('is_taken_by_booster', 'is_taken_by_booster'), ('is_returned_by_booster', 'is_returned_by_booster'), ('is_complete', 'is_complete')], db_index=True, default='is_checking', max_length=28),
        ),
    ]
