# Generated by Django 2.1 on 2019-09-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
