# Generated by Django 2.1 on 2019-09-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_auto_20190921_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
