# Generated by Django 2.1 on 2019-10-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentorder',
            name='platform',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
