# Generated by Django 2.1 on 2019-10-12 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_parentorder_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentorder',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.BungiePlatform'),
        ),
    ]
