# Generated by Django 2.1 on 2019-10-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='order_id',
            new_name='order',
        ),
    ]
