# Generated by Django 2.1 on 2019-10-20 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_auto_20191016_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booster_user',
            field=models.ForeignKey(blank=True, help_text='Booster set for current order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booster_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
