# Generated by Django 2.1 on 2019-10-22 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_auto_20191022_1745'),
        ('orders', '0046_auto_20191020_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentorder',
            name='credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.ProfileCredentials'),
        ),
    ]
