# Generated by Django 2.1 on 2019-10-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_auto_20191027_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booster_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
