# Generated by Django 2.1 on 2019-10-31 16:44

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0035_auto_20191022_1745'),
        ('services', '0046_serviceconfig_booster_price'),
        ('orders', '0050_order_booster_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('total_price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True)),
                ('booster_price', models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_id', models.CharField(db_index=True, default='', max_length=1024)),
                ('payment_status', models.CharField(blank=True, max_length=128, null=True)),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('status', models.CharField(blank=True, choices=[('is_checking_payment', 'is_checking_payment'), ('waiting_for_booster', 'waiting_for_booster'), ('in_progress', 'in_progress'), ('attempt_authorization', 'attempt_authorization'), ('two_factor_code_required', 'two_factor_code_required'), ('cant_sign_in', 'cant_sign_in'), ('paused', 'paused'), ('pending_approval', 'pending_approval'), ('is_complete', 'is_complete')], db_index=True, default='is_checking_payment', max_length=28)),
                ('is_order_complete', models.BooleanField(default=False)),
                ('is_payed', models.BooleanField(default=False)),
                ('is_posted', models.BooleanField(default=False)),
                ('complete_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('layout_options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('booster_user', models.ForeignKey(blank=True, db_constraint=False, help_text='Booster set for current order', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('bungie_profile', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='profiles.BungieID')),
                ('character', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='profiles.UserCharacter')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.ParentOrder')),
                ('promo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='services.PromoCode')),
                ('pvp_config', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.PvpConfigOrder')),
                ('service', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='services.Service')),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.Site')),
            ],
            options={
                'verbose_name': 'historical order',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.PromoCode'),
        ),
    ]
