# Generated by Django 2.1 on 2019-11-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0051_auto_20191031_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='message_sent_to_booster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='message_sent_to_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='message_sent_to_booster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='message_sent_to_client',
            field=models.BooleanField(default=False),
        ),
    ]
