# Generated by Django 2.1 on 2019-11-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0052_auto_20191114_1430"),
    ]

    operations = [
        migrations.RemoveField(model_name="historicalorder", name="booster_user",),
        migrations.RemoveField(model_name="historicalorder", name="bungie_profile",),
        migrations.RemoveField(model_name="historicalorder", name="character",),
        migrations.RemoveField(model_name="historicalorder", name="history_user",),
        migrations.RemoveField(model_name="historicalorder", name="parent_order",),
        migrations.RemoveField(model_name="historicalorder", name="promo",),
        migrations.RemoveField(model_name="historicalorder", name="pvp_config",),
        migrations.RemoveField(model_name="historicalorder", name="service",),
        migrations.RemoveField(model_name="historicalorder", name="site",),
        migrations.AddField(
            model_name="order",
            name="is_faked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=1024, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="service_config",
            field=models.ManyToManyField(
                blank=True, null=True, to="services.ServiceConfig"
            ),
        ),
        migrations.DeleteModel(name="HistoricalOrder",),
    ]
