# Generated by Django 2.1 on 2019-12-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0053_auto_20191117_1459"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
