# Generated by Django 2.1 on 2020-05-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0054_auto_20191224_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('is_checking_payment', 'is_checking_payment'), ('waiting_for_booster', 'waiting_for_booster'), ('in_progress', 'in_progress'), ('attempt_authorization', 'attempt_authorization'), ('two_factor_code_required', 'two_factor_code_required'), ('cant_sign_in', 'cant_sign_in'), ('paused', 'paused'), ('pending_approval', 'pending_approval'), ('is_complete', 'is_complete'), ('canceled', 'canceled')], db_index=True, default='is_checking_payment', max_length=28),
        ),
    ]
