# Generated by Django 3.0.8 on 2020-11-15 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0055_auto_20201113_2001'),
        ('orders', '0056_ormshoppingcart_ormshoppingcartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormshoppingcartitem',
            name='selected_options',
            field=models.ManyToManyField(to='services.ServiceConfig'),
        ),
        migrations.AddField(
            model_name='ormshoppingcartitem',
            name='service',
            field=models.ForeignKey(default='glory', on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
            preserve_default=False,
        ),
    ]
