# Generated by Django 3.0.8 on 2020-11-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_ormdestinybungiecharacter_ormdestinybungieprofile'),
        ('orders', '0057_auto_20201115_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormshoppingcartitem',
            name='bungie_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ORMDestinyBungieProfile'),
        ),
        migrations.AlterField(
            model_name='ormshoppingcartitem',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ORMDestinyBungieCharacter'),
        ),
    ]
