# Generated by Django 3.0.8 on 2020-11-23 17:35
import core.order.domain.consts
import core.order.domain.order
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0055_auto_20201113_2001'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0040_auto_20201116_1255'),
        ('orders', '0059_auto_20201117_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORMClientOrders',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('payment_id', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField()),
                ('order_status', models.CharField(choices=[('AWAIT_PAYMENT', 'AWAIT_PAYMENT'), ('PAYED', 'PAYED')], default='AWAIT_PAYMENT', max_length=32)),
                ('order_status_changed_at', models.DateTimeField()),
                ('cart_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.ORMShoppingCart')),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_orders',
            },
        ),
        migrations.CreateModel(
            name='ORMOrderObjective',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED')], default=
                core.order.domain.consts.OrderObjectiveStatus['CREATED'], max_length=32)),
                ('status_changed_at', models.DateTimeField()),
                ('booster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.BoosterUser')),
                ('client_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ORMClientOrders')),
                ('destiny_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ORMDestinyBungieCharacter')),
                ('destiny_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ORMDestinyBungieProfile')),
                ('selected_options', models.ManyToManyField(related_name='order_objectives', to='services.ServiceConfig')),
                ('service_slug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Service')),
            ],
            options={
                'db_table': 'order_objective',
            },
        ),
    ]
