# Generated by Django 3.0.8 on 2020-11-23 18:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0060_ormclientorders_ormorderobjective'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ORMClientOrders',
            new_name='ORMClientOrder',
        ),
        migrations.RenameField(
            model_name='ormclientorder',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='ormclientorder',
            old_name='client_id',
            new_name='client',
        ),
    ]
