# Generated by Django 3.0.8 on 2020-11-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0062_auto_20201123_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormclientorder',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
