# Generated by Django 3.0.8 on 2020-12-05 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0058_auto_20201129_1241'),
        ('orders', '0064_auto_20201123_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormshoppingcart',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.PromoCode'),
        ),
    ]
