# Generated by Django 3.0.8 on 2020-12-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0058_auto_20201129_1241'),
        ('orders', '0065_ormshoppingcart_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormclientorder',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ormshoppingcartitem',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='services.ServiceConfig'),
        ),
    ]
