# Generated by Django 3.0.8 on 2020-12-26 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0058_auto_20201129_1241'),
        ('profiles', '0040_auto_20201116_1255'),
        ('orders', '0068_auto_20201210_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormclientorder',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.BungiePlatform'),
        ),
        migrations.AddField(
            model_name='ormclientorder',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.PromoCode'),
        ),
    ]
