# Generated by Django 3.0.8 on 2020-12-26 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0040_auto_20201116_1255'),
        ('orders', '0069_auto_20201226_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormorderobjective',
            name='destiny_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.ORMDestinyBungieCharacter'),
        ),
        migrations.AlterField(
            model_name='ormorderobjective',
            name='destiny_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.ORMDestinyBungieProfile'),
        ),
    ]
