# Generated by Django 3.0.8 on 2020-12-27 11:10

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0070_auto_20201226_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormorderobjective',
            name='range_options',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
