# Generated by Django 3.0.8 on 2021-01-04 16:01
import core.order.domain.consts
import core.order.domain.order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0071_ormorderobjective_range_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormorderobjective',
            name='status',
            field=models.CharField(choices=[(core.order.domain.consts.OrderObjectiveStatus['CREATED'], 'Order created'), (
            core.order.domain.consts.OrderObjectiveStatus['PROCESSING'], 'In processing'), (
                                            core.order.domain.consts.OrderObjectiveStatus['AWAITING_BOOSTER'], 'Awaiting for booster to sign in'), (
                                            core.order.domain.consts.OrderObjectiveStatus['TRYING_TO_LOGIN'], 'Trying to login'), (
                                            core.order.domain.consts.OrderObjectiveStatus['REQUIRED_2FA_CODE'], 'Required 2fa code'), (
                                            core.order.domain.consts.OrderObjectiveStatus['INVALID_CREDENTIALS'], 'Invalid credentials set'), (
                                            core.order.domain.consts.OrderObjectiveStatus['IN_PROGRESS'], 'In progress'), (
                                            core.order.domain.consts.OrderObjectiveStatus['PAUSED_BOOSTER'], 'Paused booster'), (
                                            core.order.domain.consts.OrderObjectiveStatus['PAUSED_CONDITION'], 'Paused condition'), (
                                            core.order.domain.consts.OrderObjectiveStatus['PENDING_APPROVAL'], 'Pending approval'), (
                                            core.order.domain.consts.OrderObjectiveStatus['SET_REVIEW'], 'Set review'), (
                                            core.order.domain.consts.OrderObjectiveStatus['DISRUPTED'], 'Disrupted')], default=
                                   core.order.domain.consts.OrderObjectiveStatus['CREATED'], help_text='Order state', max_length=32, verbose_name='Order state'),
        ),
    ]
