# Generated by Django 3.0.8 on 2021-01-07 17:53

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0072_auto_20210104_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormorderobjective',
            name='range_options',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
