# Generated by Django 3.0.8 on 2021-01-11 18:38
import core.order.domain.consts
import core.order.domain.order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0074_auto_20210109_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormorderobjective',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Order created'), ('PROCESSING', 'In processing'), ('AWAITING_BOOSTER', 'Awaiting for booster to sign in'), ('TRYING_TO_LOGIN', 'Trying to login'), ('REQUIRED_2FA_CODE', 'Required 2fa code'), ('INVALID_CREDENTIALS', 'Invalid credentials set'), ('IN_PROGRESS', 'In progress'), ('PAUSED_BOOSTER', 'Paused booster'), ('PAUSED_CONDITION', 'Paused condition'), ('PENDING_APPROVAL', 'Pending approval'), ('SET_REVIEW', 'Set review'), ('DISRUPTED', 'Disrupted'), ('COMPLETED', 'Completed')], default=
            core.order.domain.consts.OrderObjectiveStatus['CREATED'], help_text='Order state', max_length=32, verbose_name='Order state'),
        ),
    ]
