# Generated by Django 3.0.8 on 2021-01-11 18:46

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0064_service_eta'),
        ('orders', '0075_auto_20210111_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormorderobjective',
            name='client_order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.ORMClientOrder'),
        ),
        migrations.AlterField(
            model_name='ormorderobjective',
            name='id',
            field=models.CharField(default=utils.random_guid, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ormorderobjective',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ormorderobjective',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='order_objectives', to='services.ServiceConfig'),
        ),
        migrations.AlterField(
            model_name='ormorderobjective',
            name='status_changed_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
