# Generated by Django 3.0.8 on 2021-01-11 18:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0076_auto_20210111_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormorderobjective',
            name='client_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.ORMClientOrder'),
        ),
        migrations.AlterField(
            model_name='ormorderobjective',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
