# Generated by Django 3.0.8 on 2021-01-24 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0081_auto_20210123_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormorderobjective',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
