# Generated by Django 3.0.8 on 2021-02-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0084_auto_20210207_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormclientorder',
            name='payed_with_cashback',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
